media:
  - name: docs
    label: Docs
    input: public/docs
    output: /public/docs
    categories: [ document ]
  - name: images # Note: 'name' key is required here
    label: Images
    input: public/imgs
    output: /public/imgs
    extensions: [ png, webp, jpg ]
